services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../../src/*'
    exclude: '../../src/{*Test}'

  PDO:
    class: PDO
    factory: [ '@App\Database\DatabaseConnectionFactory', 'create' ]
    arguments:
      $dsn: 'mysql:host=pickupPoints.mysql;dbname=%env(resolve:MYSQL_DATABASE)%'
      $username: '%env(resolve:MYSQL_USERNAME)%'
      $password: '%env(resolve:MYSQL_PASSWORD)%'

  App\Command\PhinxMigrationCommand:
    arguments:
      $environment: '%env(resolve:ENV)%'
      $database: '%env(resolve:MYSQL_DATABASE)%'