services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../../src/*'
    exclude:
      - '../src/**/*Test.php'

  PDO:
    class: PDO
    factory: [ '@App\Database\DatabaseConnectionFactory', 'create' ]
    arguments:
      $dsn: 'mysql:host=pickupPoints.mysql;dbname=%env(resolve:MYSQL_DATABASE)%'
      $username: '%env(resolve:MYSQL_USERNAME)%'
      $password: '%env(resolve:MYSQL_PASSWORD)%'

  App\Command\PhinxMigrationCommand:
    arguments:
      $environment: '%env(resolve:ENV)%'
      $database: '%env(resolve:MYSQL_DATABASE)%'

  App\Import\ImporterService:
    arguments:
      $importers:
        - '@App\Import\BalikovnaImporter'

  App\Import\BalikovnaImporter:
    arguments:
      $xmlReaderProvider: '@App\Import\Reader\Xml\DefaultXmlReaderProvider'
      $externalIdResolver: '@App\Import\Resolver\ExternalIdResolver'
      $pickupPointTypeResolver: '@App\Import\Resolver\Type\BalikovnaTypeResolver'
      $pickupPointStatusResolver: '@App\Import\Resolver\Status\BalikovnaStatusResolver'
      $pickupPointOpeningHoursResolver: '@App\Import\Resolver\OpeningHours\BalikovnaOpeningHoursResolver'
